// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"TA-management/internal/modules/ta_duty/dto/request"
	"TA-management/internal/modules/ta_duty/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// TaDutyRepository is an autogenerated mock type for the TaDutyRepository type
type TaDutyRepository struct {
	mock.Mock
}

// GetTADutyRoadmap provides a mock function with given fields: courseID, studentID
func (_m *TaDutyRepository) GetTADutyRoadmap(courseID int, studentID int) (*[]response.DutyChecklistItem, error) {
	ret := _m.Called(courseID, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTADutyRoadmap")
	}

	var r0 *[]response.DutyChecklistItem
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*[]response.DutyChecklistItem, error)); ok {
		return rf(courseID, studentID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *[]response.DutyChecklistItem); ok {
		r0 = rf(courseID, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.DutyChecklistItem)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(courseID, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkDutyAsDone provides a mock function with given fields: courseID, studentID, dutyDate
func (_m *TaDutyRepository) MarkDutyAsDone(courseID int, studentID int, dutyDate string) error {
	ret := _m.Called(courseID, studentID, dutyDate)

	if len(ret) == 0 {
		panic("no return value specified for MarkDutyAsDone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, string) error); ok {
		r0 = rf(courseID, studentID, dutyDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTADutyDataExportPayment provides a mock function with given fields: courseID, month
func (_m *TaDutyRepository) GetTADutyDataExportPayment(courseID int, month int) (*[]request.CreatePaymentData, *request.CourseDutyData, error) {
	ret := _m.Called(courseID, month)

	if len(ret) == 0 {
		panic("no return value specified for GetTADutyDataExportPayment")
	}

	var r0 *[]request.CreatePaymentData
	var r1 *request.CourseDutyData
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) (*[]request.CreatePaymentData, *request.CourseDutyData, error)); ok {
		return rf(courseID, month)
	}
	if rf, ok := ret.Get(0).(func(int, int) *[]request.CreatePaymentData); ok {
		r0 = rf(courseID, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]request.CreatePaymentData)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) *request.CourseDutyData); ok {
		r1 = rf(courseID, month)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*request.CourseDutyData)
		}
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(courseID, month)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTADutyDataExportSignature provides a mock function with given fields: courseID, month
func (_m *TaDutyRepository) GetTADutyDataExportSignature(courseID int, month int) (*request.CreateSignatureSheet, *request.CourseDutyData, error) {
	ret := _m.Called(courseID, month)

	if len(ret) == 0 {
		panic("no return value specified for GetTADutyDataExportSignature")
	}

	var r0 *request.CreateSignatureSheet
	var r1 *request.CourseDutyData
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) (*request.CreateSignatureSheet, *request.CourseDutyData, error)); ok {
		return rf(courseID, month)
	}
	if rf, ok := ret.Get(0).(func(int, int) *request.CreateSignatureSheet); ok {
		r0 = rf(courseID, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.CreateSignatureSheet)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) *request.CourseDutyData); ok {
		r1 = rf(courseID, month)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*request.CourseDutyData)
		}
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(courseID, month)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTaDutyRepository creates a new instance of TaDutyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTaDutyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaDutyRepository {
	mock := &TaDutyRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
