// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"TA-management/internal/modules/student/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// StudentRepository is an autogenerated mock type for the StudentRepository type
type StudentRepository struct {
	mock.Mock
}

// GetStudentByID provides a mock function with given fields: studentID
func (_m *StudentRepository) GetStudentByID(studentID int) (*response.StudentProfile, error) {
	ret := _m.Called(studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentByID")
	}

	var r0 *response.StudentProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*response.StudentProfile, error)); ok {
		return rf(studentID)
	}
	if rf, ok := ret.Get(0).(func(int) *response.StudentProfile); ok {
		r0 = rf(studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.StudentProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStudent provides a mock function with given fields: studentID, firstnameThai, lastnameThai, phoneNumber
func (_m *StudentRepository) UpdateStudent(studentID int, firstnameThai string, lastnameThai string, phoneNumber string) error {
	ret := _m.Called(studentID, firstnameThai, lastnameThai, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string, string) error); ok {
		r0 = rf(studentID, firstnameThai, lastnameThai, phoneNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadDocument provides a mock function with given fields: studentID, docType, fileBytes, fileName
func (_m *StudentRepository) UploadDocument(studentID int, docType string, fileBytes []byte, fileName string) error {
	ret := _m.Called(studentID, docType, fileBytes, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, []byte, string) error); ok {
		r0 = rf(studentID, docType, fileBytes, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDocument provides a mock function with given fields: studentID, docType
func (_m *StudentRepository) GetDocument(studentID int, docType string) ([]byte, string, error) {
	ret := _m.Called(studentID, docType)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(int, string) ([]byte, string, error)); ok {
		return rf(studentID, docType)
	}
	if rf, ok := ret.Get(0).(func(int, string) []byte); ok {
		r0 = rf(studentID, docType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) string); ok {
		r1 = rf(studentID, docType)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(int, string) error); ok {
		r2 = rf(studentID, docType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeleteDocument provides a mock function with given fields: studentID, docType
func (_m *StudentRepository) DeleteDocument(studentID int, docType string) error {
	ret := _m.Called(studentID, docType)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(studentID, docType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckDocumentExists provides a mock function with given fields: studentID, docType
func (_m *StudentRepository) CheckDocumentExists(studentID int, docType string) (bool, error) {
	ret := _m.Called(studentID, docType)

	if len(ret) == 0 {
		panic("no return value specified for CheckDocumentExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (bool, error)); ok {
		return rf(studentID, docType)
	}
	if rf, ok := ret.Get(0).(func(int, string) bool); ok {
		r0 = rf(studentID, docType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(studentID, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStudentRepository creates a new instance of StudentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStudentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentRepository {
	mock := &StudentRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
