// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"TA-management/internal/modules/announce/dto/request"
	"TA-management/internal/modules/announce/dto/response"

	mock "github.com/stretchr/testify/mock"
)

// AnnouncementRepository is an autogenerated mock type for the AnnouncementRepository type
type AnnouncementRepository struct {
	mock.Mock
}

// GetStudentEmailByCourseIDs provides a mock function with no fields
func (_m *AnnouncementRepository) GetStudentEmailByCourseIDs() (*request.EmailRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStudentEmailByCourseIDs")
	}

	var r0 *request.EmailRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() (*request.EmailRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *request.EmailRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.EmailRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentEmailByCourseID provides a mock function with given fields: courseID
func (_m *AnnouncementRepository) GetStudentEmailByCourseID(courseID int) (*request.EmailRequest, *response.CourseDetail, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentEmailByCourseID")
	}

	var r0 *request.EmailRequest
	var r1 *response.CourseDetail
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (*request.EmailRequest, *response.CourseDetail, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(int) *request.EmailRequest); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.EmailRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *response.CourseDetail); ok {
		r1 = rf(courseID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*response.CourseDetail)
		}
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(courseID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStudentEmailByStudentID provides a mock function with given fields: studentID
func (_m *AnnouncementRepository) GetStudentEmailByStudentID(studentID int) (*request.EmailRequest, error) {
	ret := _m.Called(studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentEmailByStudentID")
	}

	var r0 *request.EmailRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*request.EmailRequest, error)); ok {
		return rf(studentID)
	}
	if rf, ok := ret.Get(0).(func(int) *request.EmailRequest); ok {
		r0 = rf(studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.EmailRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveEmailHistory provides a mock function with given fields: rq
func (_m *AnnouncementRepository) SaveEmailHistory(rq request.CreateEmailHistory) error {
	ret := _m.Called(rq)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmailHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.CreateEmailHistory) error); ok {
		r0 = rf(rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEmailHistory provides a mock function with no fields
func (_m *AnnouncementRepository) GetEmailHistory() (*[]response.EmailHistory, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmailHistory")
	}

	var r0 *[]response.EmailHistory
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]response.EmailHistory, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]response.EmailHistory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.EmailHistory)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDiscordRoleID provides a mock function with given fields: courseID
func (_m *AnnouncementRepository) GetDiscordRoleID(courseID int) (string, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetDiscordRoleID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(courseID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNewDiscordChannel provides a mock function with given fields: roleID, channelID, channelName, courseID
func (_m *AnnouncementRepository) CreateNewDiscordChannel(roleID string, channelID string, channelName string, courseID int) error {
	ret := _m.Called(roleID, channelID, channelName, courseID)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewDiscordChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, int) error); ok {
		r0 = rf(roleID, channelID, channelName, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAnnouncementRepository creates a new instance of AnnouncementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAnnouncementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnouncementRepository {
	mock := &AnnouncementRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
