// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dtoresponse "TA-management/internal/modules/shared/dto/response"

	mock "github.com/stretchr/testify/mock"

	request "TA-management/internal/modules/course/dto/request"

	response "TA-management/internal/modules/course/dto/response"

	sql "database/sql"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// CheckStudentJobpostStatus provides a mock function with given fields: body
func (_m *CourseRepository) CheckStudentJobpostStatus(body request.ApplyJobPost) (bool, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CheckStudentJobpostStatus")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(request.ApplyJobPost) (bool, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(request.ApplyJobPost) bool); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(request.ApplyJobPost) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitTx provides a mock function with given fields: tx
func (_m *CourseRepository) CommitTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountTaAllocation provides a mock function with given fields: jobPostID
func (_m *CourseRepository) CountTaAllocation(jobPostID int) (int, error) {
	ret := _m.Called(jobPostID)

	if len(ret) == 0 {
		panic("no return value specified for CountTaAllocation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(jobPostID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(jobPostID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(jobPostID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCourse provides a mock function with given fields: body
func (_m *CourseRepository) CreateCourse(body request.CreateCourse) (int, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CreateCourse) (int, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(request.CreateCourse) int); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(request.CreateCourse) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateJobPost provides a mock function with given fields: body
func (_m *CourseRepository) CreateJobPost(body request.CreateJobPost) (int, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobPost")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CreateJobPost) (int, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(request.CreateJobPost) int); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(request.CreateJobPost) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCourse provides a mock function with given fields: id
func (_m *CourseRepository) DeleteCourse(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteJobPost provides a mock function with given fields: jobPostId
func (_m *CourseRepository) DeleteJobPost(jobPostId int) error {
	ret := _m.Called(jobPostId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(jobPostId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCourse provides a mock function with no fields
func (_m *CourseRepository) GetAllCourse() ([]response.Course, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCourse")
	}

	var r0 []response.Course
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]response.Course, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []response.Course); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Course)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllJobPost provides a mock function with no fields
func (_m *CourseRepository) GetAllJobPost() ([]response.JobPost, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllJobPost")
	}

	var r0 []response.JobPost
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]response.JobPost, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []response.JobPost); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.JobPost)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllJobPostAllStatus provides a mock function with no fields
func (_m *CourseRepository) GetAllJobPostAllStatus() ([]response.JobPost, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllJobPostAllStatus")
	}

	var r0 []response.JobPost
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]response.JobPost, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []response.JobPost); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.JobPost)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllJobPostByStudentId provides a mock function with given fields: studentId
func (_m *CourseRepository) GetAllJobPostByStudentId(studentId int) ([]response.JobPost, error) {
	ret := _m.Called(studentId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllJobPostByStudentId")
	}

	var r0 []response.JobPost
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]response.JobPost, error)); ok {
		return rf(studentId)
	}
	if rf, ok := ret.Get(0).(func(int) []response.JobPost); ok {
		r0 = rf(studentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.JobPost)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(studentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTimeApprovedCoursesByStudentId provides a mock function with given fields: studentId
func (_m *CourseRepository) GetAllTimeApprovedCoursesByStudentId(studentId int) ([]response.Application, error) {
	ret := _m.Called(studentId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTimeApprovedCoursesByStudentId")
	}

	var r0 []response.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]response.Application, error)); ok {
		return rf(studentId)
	}
	if rf, ok := ret.Get(0).(func(int) []response.Application); ok {
		r0 = rf(studentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(studentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationBankAccountPdf provides a mock function with given fields: ApplicationId
func (_m *CourseRepository) GetApplicationBankAccountPdf(ApplicationId int) (*response.PdfFile, error) {
	ret := _m.Called(ApplicationId)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationBankAccountPdf")
	}

	var r0 *response.PdfFile
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*response.PdfFile, error)); ok {
		return rf(ApplicationId)
	}
	if rf, ok := ret.Get(0).(func(int) *response.PdfFile); ok {
		r0 = rf(ApplicationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PdfFile)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ApplicationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationByCourseId provides a mock function with given fields: courseId
func (_m *CourseRepository) GetApplicationByCourseId(courseId int) ([]response.Application, error) {
	ret := _m.Called(courseId)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationByCourseId")
	}

	var r0 []response.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]response.Application, error)); ok {
		return rf(courseId)
	}
	if rf, ok := ret.Get(0).(func(int) []response.Application); ok {
		r0 = rf(courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationByProfessorId provides a mock function with given fields: professorId
func (_m *CourseRepository) GetApplicationByProfessorId(professorId int) ([]response.Application, error) {
	ret := _m.Called(professorId)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationByProfessorId")
	}

	var r0 []response.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]response.Application, error)); ok {
		return rf(professorId)
	}
	if rf, ok := ret.Get(0).(func(int) []response.Application); ok {
		r0 = rf(professorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(professorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationByStudentId provides a mock function with given fields: studentId
func (_m *CourseRepository) GetApplicationByStudentId(studentId int) ([]response.Application, error) {
	ret := _m.Called(studentId)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationByStudentId")
	}

	var r0 []response.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]response.Application, error)); ok {
		return rf(studentId)
	}
	if rf, ok := ret.Get(0).(func(int) []response.Application); ok {
		r0 = rf(studentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(studentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationDetail provides a mock function with given fields: ApplicationId
func (_m *CourseRepository) GetApplicationDetail(ApplicationId int) (*response.Application, error) {
	ret := _m.Called(ApplicationId)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationDetail")
	}

	var r0 *response.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*response.Application, error)); ok {
		return rf(ApplicationId)
	}
	if rf, ok := ret.Get(0).(func(int) *response.Application); ok {
		r0 = rf(ApplicationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ApplicationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationStudentCardPdf provides a mock function with given fields: ApplicationId
func (_m *CourseRepository) GetApplicationStudentCardPdf(ApplicationId int) (*response.PdfFile, error) {
	ret := _m.Called(ApplicationId)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationStudentCardPdf")
	}

	var r0 *response.PdfFile
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*response.PdfFile, error)); ok {
		return rf(ApplicationId)
	}
	if rf, ok := ret.Get(0).(func(int) *response.PdfFile); ok {
		r0 = rf(ApplicationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PdfFile)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ApplicationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplicationTranscriptPdf provides a mock function with given fields: ApplicationId
func (_m *CourseRepository) GetApplicationTranscriptPdf(ApplicationId int) (*response.PdfFile, error) {
	ret := _m.Called(ApplicationId)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationTranscriptPdf")
	}

	var r0 *response.PdfFile
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*response.PdfFile, error)); ok {
		return rf(ApplicationId)
	}
	if rf, ok := ret.Get(0).(func(int) *response.PdfFile); ok {
		r0 = rf(ApplicationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PdfFile)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ApplicationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApproveApplicationData provides a mock function with given fields: applicationData
func (_m *CourseRepository) GetApproveApplicationData(applicationData int) (int, int, int, error) {
	ret := _m.Called(applicationData)

	if len(ret) == 0 {
		panic("no return value specified for GetApproveApplicationData")
	}

	var r0 int
	var r1 int
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(int) (int, int, int, error)); ok {
		return rf(applicationData)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(applicationData)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) int); ok {
		r1 = rf(applicationData)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int) int); ok {
		r2 = rf(applicationData)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(int) error); ok {
		r3 = rf(applicationData)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetCoursesBySemesterID provides a mock function with given fields: semesterID
func (_m *CourseRepository) GetCoursesBySemesterID(semesterID int) (*dtoresponse.RequestDataResponse, error) {
	ret := _m.Called(semesterID)

	if len(ret) == 0 {
		panic("no return value specified for GetCoursesBySemesterID")
	}

	var r0 *dtoresponse.RequestDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*dtoresponse.RequestDataResponse, error)); ok {
		return rf(semesterID)
	}
	if rf, ok := ret.Get(0).(func(int) *dtoresponse.RequestDataResponse); ok {
		r0 = rf(semesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtoresponse.RequestDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(semesterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDiscordRoleByCourseId provides a mock function with given fields: courseId
func (_m *CourseRepository) GetDiscordRoleByCourseId(courseId int) (string, error) {
	ret := _m.Called(courseId)

	if len(ret) == 0 {
		panic("no return value specified for GetDiscordRoleByCourseId")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(courseId)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(courseId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiredSemesters provides a mock function with no fields
func (_m *CourseRepository) GetExpiredSemesters() (*dtoresponse.RequestDataResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredSemesters")
	}

	var r0 *dtoresponse.RequestDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*dtoresponse.RequestDataResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *dtoresponse.RequestDataResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtoresponse.RequestDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobPostByID provides a mock function with given fields: jobPostId
func (_m *CourseRepository) GetJobPostByID(jobPostId int) (*response.JobPost, error) {
	ret := _m.Called(jobPostId)

	if len(ret) == 0 {
		panic("no return value specified for GetJobPostByID")
	}

	var r0 *response.JobPost
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*response.JobPost, error)); ok {
		return rf(jobPostId)
	}
	if rf, ok := ret.Get(0).(func(int) *response.JobPost); ok {
		r0 = rf(jobPostId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.JobPost)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(jobPostId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfessorCourse provides a mock function with given fields: professorId
func (_m *CourseRepository) GetProfessorCourse(professorId int) ([]response.Course, error) {
	ret := _m.Called(professorId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfessorCourse")
	}

	var r0 []response.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]response.Course, error)); ok {
		return rf(professorId)
	}
	if rf, ok := ret.Get(0).(func(int) []response.Course); ok {
		r0 = rf(professorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(professorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaAllocation provides a mock function with given fields: jobPostID
func (_m *CourseRepository) GetTaAllocation(jobPostID int) (int, error) {
	ret := _m.Called(jobPostID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaAllocation")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(jobPostID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(jobPostID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(jobPostID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertApplication provides a mock function with given fields: tx, body
func (_m *CourseRepository) InsertApplication(tx *sql.Tx, body request.ApplyJobPost) (int, error) {
	ret := _m.Called(tx, body)

	if len(ret) == 0 {
		panic("no return value specified for InsertApplication")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*sql.Tx, request.ApplyJobPost) (int, error)); ok {
		return rf(tx, body)
	}
	if rf, ok := ret.Get(0).(func(*sql.Tx, request.ApplyJobPost) int); ok {
		r0 = rf(tx, body)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*sql.Tx, request.ApplyJobPost) error); ok {
		r1 = rf(tx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTaCourse provides a mock function with given fields: tx, studentId, courseId
func (_m *CourseRepository) InsertTaCourse(tx *sql.Tx, studentId int, courseId int) error {
	ret := _m.Called(tx, studentId, courseId)

	if len(ret) == 0 {
		panic("no return value specified for InsertTaCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx, int, int) error); ok {
		r0 = rf(tx, studentId, courseId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsCourseExist provides a mock function with given fields: body
func (_m *CourseRepository) IsCourseExist(body request.CreateCourse) (int, error) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for IsCourseExist")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CreateCourse) (int, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(request.CreateCourse) int); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(request.CreateCourse) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectApplication provides a mock function with given fields: rq
func (_m *CourseRepository) RejectApplication(rq request.RejectApplication) error {
	ret := _m.Called(rq)

	if len(ret) == 0 {
		panic("no return value specified for RejectApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.RejectApplication) error); ok {
		r0 = rf(rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackTx provides a mock function with given fields: tx
func (_m *CourseRepository) RollbackTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteExpiredData provides a mock function with no fields
func (_m *CourseRepository) SoftDeleteExpiredData() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteExpiredData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartDBTx provides a mock function with no fields
func (_m *CourseRepository) StartDBTx() (*sql.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartDBTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateApplicationStatus provides a mock function with given fields: tx, ApplicationId
func (_m *CourseRepository) UpdateApplicationStatus(tx *sql.Tx, ApplicationId int) error {
	ret := _m.Called(tx, ApplicationId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApplicationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx, int) error); ok {
		r0 = rf(tx, ApplicationId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCourse provides a mock function with given fields: body
func (_m *CourseRepository) UpdateCourse(body request.UpdateCourse) error {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.UpdateCourse) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCourseDiscord provides a mock function with given fields: courseId, roleId, channelId, channelName
func (_m *CourseRepository) UpdateCourseDiscord(courseId int, roleId string, channelId string, channelName string) error {
	ret := _m.Called(courseId, roleId, channelId, channelName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourseDiscord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string, string) error); ok {
		r0 = rf(courseId, roleId, channelId, channelName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateJobPost provides a mock function with given fields: body
func (_m *CourseRepository) UpdateJobPost(body request.UpdateJobPost) error {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.UpdateJobPost) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateJobPostStatus provides a mock function with given fields: jobPostId
func (_m *CourseRepository) UpdateJobPostStatus(jobPostId int) error {
	ret := _m.Called(jobPostId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobPostStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(jobPostId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStudentData provides a mock function with given fields: tx, body
func (_m *CourseRepository) UpdateStudentData(tx *sql.Tx, body request.ApplyJobPost) error {
	ret := _m.Called(tx, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStudentData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx, request.ApplyJobPost) error); ok {
		r0 = rf(tx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertBankAccount provides a mock function with given fields: tx, body
func (_m *CourseRepository) UpsertBankAccount(tx *sql.Tx, body request.ApplyJobPost) error {
	ret := _m.Called(tx, body)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBankAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx, request.ApplyJobPost) error); ok {
		r0 = rf(tx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertStudentCard provides a mock function with given fields: tx, body
func (_m *CourseRepository) UpsertStudentCard(tx *sql.Tx, body request.ApplyJobPost) error {
	ret := _m.Called(tx, body)

	if len(ret) == 0 {
		panic("no return value specified for UpsertStudentCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx, request.ApplyJobPost) error); ok {
		r0 = rf(tx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertTranscript provides a mock function with given fields: tx, body
func (_m *CourseRepository) UpsertTranscript(tx *sql.Tx, body request.ApplyJobPost) error {
	ret := _m.Called(tx, body)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTranscript")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx, request.ApplyJobPost) error); ok {
		r0 = rf(tx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
